### ISSUE TITLE
打开App闪退

### ISSUE THREAD

**Issue by AllinProgram** [xinpengfei520/pgyer-android-app-update#1]
你好，感谢您的集成工具。

我将他加入到我的app中，会发生闪退，并且我没有捕捉到异常日志。

我将复现的代码demo上传到此处：https://github.com/ufan0/nodebb

我确定是的我使用方式有误，希望能得到您的指导，感激不尽。

**Comment by AllinProgram** [comment]
我终于找到了我的错误，犯了一个非常低级的错误，再次感谢您的这个集成工具。

**Comment by xinpengfei520** [comment]
什么问题呢？贴出来看看，也避免其他人掉坑。

**Comment by AllinProgram** [comment]
闪退原因：源码以及demo中没有添加api key，仅仅加上了app key。

抱歉浪费您的时间，这是一个愚蠢至极的错误。
